# Generated by Django 4.2.1 on 2023-06-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='../static/image/default_img.png', max_length=255),
        ),
    ]
