# Generated by Django 4.2.1 on 2023-07-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Red', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=20),
        ),
        migrations.AddField(
            model_name='product',
            name='modelName',
            field=models.CharField(default='Doll', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
        ),
    ]
