# Generated by Django 4.2.1 on 2023-07-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_color_product_height_product_modelname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/image/default_img.png', upload_to="{{static 'products_img'}}"),
        ),
    ]
